<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IdeasSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ideas')->insert([
            ['brand_id' => 1, 'user_id' => 1, 'title' => 'FEBO kan een gezondere, plantaardige optie voor snackbar snacks introduceren om ', 'description' => 'FEBO kan een gezondere, plantaardige optie voor snackbar snacks introduceren om een breder publiek aan te trekken en gezondheidsoverwegingen te maken.', 'likes' => 1, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-31 19:54:01', 'updated_at' => '2025-08-03 19:54:01',],
            ['brand_id' => 2, 'user_id' => 1, 'title' => 'Videoland kan een optie introduceren om inhoud off-line te bekijken, waardoor ge', 'description' => 'Videoland kan een optie introduceren om inhoud off-line te bekijken, waardoor gebruikers hun favoriete films en series kunnen downloaden en bekijken zonder internetverbinding.', 'likes' => 1, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-01 19:54:01', 'updated_at' => '2025-08-05 19:54:01',],
            ['brand_id' => 3, 'user_id' => 1, 'title' => 'Topnotch kan de ervaring van het luisteren naar muziek voor hun fans verbeteren ', 'description' => 'Topnotch kan de ervaring van het luisteren naar muziek voor hun fans verbeteren door exclusieve live-optredens of behind-the-scenes content van hun artiesten op hun website te publiceren.', 'likes' => 5, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-26 19:54:01', 'updated_at' => '2025-07-27 19:54:01',],
            ['brand_id' => 4, 'user_id' => 1, 'title' => 'HEMA kan een elektronische klantenkaart introduceren die app-gebaseerd is, met l', 'description' => 'HEMA kan een elektronische klantenkaart introduceren die app-gebaseerd is, met loyauteitsbeloningen en kortingen om klantenbinding en consistentie in aankopen te aanmoedigen.', 'likes' => 3, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-17 19:54:01', 'updated_at' => '2025-08-18 19:54:01',],
            ['brand_id' => 5, 'user_id' => 1, 'title' => 'Awakenings kan profiteren van het aanbieden van een virtual reality-ervaring van', 'description' => 'Awakenings kan profiteren van het aanbieden van een virtual reality-ervaring van het festival voor degenen die niet fysiek aanwezig kunnen zijn.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-29 19:54:01', 'updated_at' => '2025-08-01 19:54:01',],
            ['brand_id' => 1, 'user_id' => 2, 'title' => 'FEBO kan overwegen om hun menu uit te breiden met veganistische en vegetarische ', 'description' => 'FEBO kan overwegen om hun menu uit te breiden met veganistische en vegetarische opties om mee te gaan met de groeiende trend van plantaardige voeding.', 'likes' => 0, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-30 19:54:01', 'updated_at' => '2025-07-31 19:54:01',],
            ['brand_id' => 2, 'user_id' => 2, 'title' => 'Videoland kan het platform verbeteren door meer internationale films en programm', 'description' => 'Videoland kan het platform verbeteren door meer internationale films en programma\'s aan te bieden. Dit kan hun bereik en aantrekkingskracht vergroten bij een breder publiek.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-08 19:54:01', 'updated_at' => '2025-08-09 19:54:01',],
            ['brand_id' => 3, 'user_id' => 2, 'title' => 'Topnotch kan hun digitale aanwezigheid vergroten door het hosten van livestreams', 'description' => 'Topnotch kan hun digitale aanwezigheid vergroten door het hosten van livestreams van hun artiesten, of het bieden van exclusieve, achter de schermen content op hun website.', 'likes' => 1, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-14 19:54:01', 'updated_at' => '2025-08-15 19:54:01',],
            ['brand_id' => 4, 'user_id' => 2, 'title' => 'HEMA kan overwegen om een mobiele app te ontwikkelen om online winkelen eenvoudi', 'description' => 'HEMA kan overwegen om een mobiele app te ontwikkelen om online winkelen eenvoudiger en aantrekkelijker te maken.', 'likes' => 0, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-09 19:54:01', 'updated_at' => '2025-08-10 19:54:01',],
            ['brand_id' => 5, 'user_id' => 2, 'title' => 'Awakenings kan hun festival verbeteren door een app te ontwikkelen die onder and', 'description' => 'Awakenings kan hun festival verbeteren door een app te ontwikkelen die onder andere realtime updates, plattegronden, timetable en de mogelijkheid tot het maken van een persoonlijk schema biedt.', 'likes' => 1, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-29 19:54:01', 'updated_at' => '2025-08-02 19:54:01',],
            ['brand_id' => 1, 'user_id' => 3, 'title' => 'Om FEBO nog beter te maken zou het geweldig zijn om een app te ontwikkelen waar ', 'description' => 'Om FEBO nog beter te maken zou het geweldig zijn om een app te ontwikkelen waar klanten hun eigen snacks kunnen personaliseren. Deze app kan het mogelijk maken om ingrediënten toe te voegen of weg te laten aan bestaande snacks, creëer je eigen burger met toppings naar keuze, of zelfs bedenk eigen unieke snackcombinaties. Na betaling in de app worden de snacks vervolgens vers bereid in de gekozen FEBO vestiging.', 'likes' => 4, 'dislikes' => 1, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-29 19:54:01', 'updated_at' => '2025-08-01 19:54:01',],
            ['brand_id' => 2, 'user_id' => 3, 'title' => 'Voor Videoland is het essentieel om unieke content te blijven produceren', 'description' => 'Voor Videoland is het essentieel om unieke content te blijven produceren. Tegenwoordig waarderen mensen diversiteit en inclusiviteit zeer, daarom is het belangrijk om reeksen te maken die verschillende verhalen en culturen vertegenwoordigen. Een andere manier om uniek te blijven is door interactieve films of series aan te bieden, waarbij de kijker het verhaal kan beïnvloeden door op bepaalde momenten in de film te kiezen wat de personages moeten doen.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-30 19:54:01', 'updated_at' => '2025-08-01 19:54:01',],
            ['brand_id' => 3, 'user_id' => 3, 'title' => 'Topnotch kan een muziekwedstrijd organiseren om nieuwe talenten te ontdekken', 'description' => 'Topnotch kan een muziekwedstrijd organiseren om nieuwe talenten te ontdekken. De winnaar krijgt de kans om een nummer op te nemen met een bekende Topnotch-artiest. Dit zou niet alleen meer aandacht en afwisseling brengen, maar ook mogelijk een heel nieuw publiek bereiken.', 'likes' => 5, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-21 19:54:01', 'updated_at' => '2025-07-23 19:54:01',],
            ['brand_id' => 4, 'user_id' => 3, 'title' => 'HEMA kan een \'Ontwerp je eigen product\' hoekje opzetten in de winkels', 'description' => 'HEMA kan een \'Ontwerp je eigen product\' hoekje opzetten in de winkels. Op deze manier kunnen de klanten een persoonlijk tintje geven aan de producten door hun naam of favoriete zin erop te laten zetten. Dit zou ook een fantastisch cadeau-idee zijn!', 'likes' => 5, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-04 19:54:01', 'updated_at' => '2025-08-07 19:54:01',],
            ['brand_id' => 5, 'user_id' => 3, 'title' => 'Om bezoekers van het Awakenings festival een unieke ervaring te bieden, kan de o', 'description' => 'Om bezoekers van het Awakenings festival een unieke ervaring te bieden, kan de organisatie VR technologie implementeren tijdens shows, waardoor concertgangers volledig kunnen onderdompelen en het gevoel hebben dat ze deel uitmaken van de show.', 'likes' => 3, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-14 19:54:01', 'updated_at' => '2025-08-17 19:54:01',],
            ['brand_id' => 1, 'user_id' => 4, 'title' => 'Met een nieuwe \'Febo Favourites\' reeks kan Febo classic en populaire snacks heri', 'description' => 'Met een nieuwe \'Febo Favourites\' reeks kan Febo classic en populaire snacks herintroduceren met een moderne twist voor een beperkte tijd.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-19 19:54:01', 'updated_at' => '2025-07-20 19:54:01',],
            ['brand_id' => 2, 'user_id' => 4, 'title' => 'Videoland kan een platform bieden voor lokale filmmakers en host een maandelijks', 'description' => 'Videoland kan een platform bieden voor lokale filmmakers en host een maandelijkse \'Indie Movie Night', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-25 19:54:01', 'updated_at' => '2025-07-29 19:54:01',],
            ['brand_id' => 3, 'user_id' => 4, 'title' => 'Topnotch zou een online platform kunnen creëren voor beginnende artiesten om hun', 'description' => 'Topnotch zou een online platform kunnen creëren voor beginnende artiesten om hun werk te delen en feedback te krijgen van meer ervaren muzikanten.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-03 19:54:01', 'updated_at' => '2025-08-03 19:54:01',],
            ['brand_id' => 4, 'user_id' => 4, 'title' => 'Hema kan hun duurzaamheidsinspanningen vergroten door een \'Refill en Save\' progr', 'description' => 'Hema kan hun duurzaamheidsinspanningen vergroten door een \'Refill en Save\' programma te introduceren op geselecteerde producten.', 'likes' => 5, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-10 19:54:01', 'updated_at' => '2025-08-10 19:54:01',],
            ['brand_id' => 5, 'user_id' => 4, 'title' => 'Awakenings kan een virtuele realiteit ervaring aanbieden waar fans een set van h', 'description' => 'Awakenings kan een virtuele realiteit ervaring aanbieden waar fans een set van hun favoriete DJ kunnen ervaren in een intieme setting, gecureerd door Awakenings.', 'likes' => 2, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-02 19:54:01', 'updated_at' => '2025-08-02 19:54:01',],
            ['brand_id' => 1, 'user_id' => 5, 'title' => 'FEBO kan zijn online zichtbaarheid vergroten met een app waar klanten hun favori', 'description' => 'FEBO kan zijn online zichtbaarheid vergroten met een app waar klanten hun favoriete snacks van tevoren kunnen bestellen en betalen, en dan gewoon oppikken bij een plaatselijke vestiging. Dit vermindert de wachttijd en verbetert de klantbeleving.', 'likes' => 2, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-02 19:54:01', 'updated_at' => '2025-08-05 19:54:01',],
            ['brand_id' => 2, 'user_id' => 5, 'title' => 'Videoland kan een functie ontwikkelen waarmee gebruikers hun favoriete series en', 'description' => 'Videoland kan een functie ontwikkelen waarmee gebruikers hun favoriete series en films kunnen markeren en gemakkelijk terug kunnen vinden. Dit zou hen een meer gepersonaliseerde ervaring bieden en hen aanmoedigen om meer inhoud te consumeren.', 'likes' => 0, 'dislikes' => 1, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-23 19:54:01', 'updated_at' => '2025-07-23 19:54:01',],
            ['brand_id' => 3, 'user_id' => 5, 'title' => 'TopNotch kan zijn bereik vergroten door online concerten en exclusieve online lu', 'description' => 'TopNotch kan zijn bereik vergroten door online concerten en exclusieve online luistersessies met hun artiesten aan te bieden. Dit kan hen helpen hun fanbase te vergroten en tegelijkertijd inkomsten genereren.', 'likes' => 1, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-14 19:54:01', 'updated_at' => '2025-08-14 19:54:01',],
            ['brand_id' => 4, 'user_id' => 5, 'title' => 'HEMA kan een abonnementsdienst beginnen waarbij klanten maandelijks een doos met', 'description' => 'HEMA kan een abonnementsdienst beginnen waarbij klanten maandelijks een doos met verschillende HEMA-producten ontvangen. Dit bevordert klantloyaliteit en verhoogt de verkoop.', 'likes' => 4, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-08-01 19:54:01', 'updated_at' => '2025-08-04 19:54:01',],
            ['brand_id' => 5, 'user_id' => 5, 'title' => 'Awakenings kan VR-concerten aanbieden voor degenen die niet in staat zijn om het', 'description' => 'Awakenings kan VR-concerten aanbieden voor degenen die niet in staat zijn om het festival persoonlijk bij te wonen. Dit zal hen helpen een breder publiek te bereiken en extra inkomsten te genereren.', 'likes' => 5, 'dislikes' => 0, 'is_pinned' => 0, 'category' => null, 'status' => 'pending', 'created_at' => '2025-07-27 19:54:01', 'updated_at' => '2025-07-27 19:54:01',],
        ]);
    }
}
